engines:
  csslint:
    enabled: true
    checks:
      order-alphabetical:
        enabled: false
      import:
        enabled: false
      box-model:
        enabled: false
      overqualified-elements:
        enabled: false
      ids:
        enabled: false
      floats:
        enabled: false

  fixme:
    enabled: true
ratings:
  paths:
  - "assets/css/**.css"
exclude_paths:
- "**/assets/fonts/**/*"
- "**/*.min.css"
- "colorized.css"
- "Gruntfile.js"
