language: node_js
node_js: 6

addons:
    code_climate:
        repo_token: f61c90bc756633a3ac51bf2a50ce341b80b4cc2496d6d93efa58eaea31147896

before_script:
 - npm install PrettyCSS -g
script:
 - prettycss --ignore=suggest-relative-unit --ignore=browser-unsupported:ie7 --ignore=browser-quirk:ie7 --ignore-all ./assets/css/open-sans.css
 - prettycss --ignore=suggest-relative-unit --ignore=browser-unsupported:ie7 --ignore-all ./assets/css/buttons.css
 - prettycss --ignore=suggest-relative-unit --ignore=browser-unsupported:ie7 --ignore-all ./assets/css/colorized.css
 - prettycss --ignore=suggest-relative-unit --ignore=browser-unsupported:ie7 --ignore-all ./assets/css/default.css
after_script:
 - npm install -g codeclimate-test-reporter
 - codeclimate-test-reporter < ./coverage/lcov.info
